language: go

go:
 - 1.12.x
 - 1.13.x

os: linux
dist: xenial

sudo: false

branches:
  only:
  - master

notifications:
  email:
    on_success: change
    on_failure: always

env:
  - PATH=$HOME/protoc/bin:$PATH
  - DATASTORE_EMULATOR_HOST=127.0.0.1:8081
  - DATASTORE_EMULATOR_HOST_PATH=127.0.0.1:8081/datastore
  - DATASTORE_HOST=http://127.0.0.1:8081
  - DATASTORE_PROJECT_ID=translator-tests

install:
  - go get -u github.com/golang/protobuf/protoc-gen-go
  - curl -L https://github.com/protocolbuffers/protobuf/releases/download/v3.9.1/protoc-3.9.1-linux-x86_64.zip -o /tmp/protoc.zip
  - unzip /tmp/protoc.zip -d "$HOME"/protoc
  - mkdir -p "$HOME"/src && ln -s "$HOME"/protoc "$HOME"/src/protobuf

script:
  - echo "Generate protobuf's"
  - make protobuf
  - cd datastore-translator
  - echo "Run unit tests"
  - go test -v ./... -race -coverprofile=coverage.txt -covermode=atomic
  - echo "Run integration tests"
  - go test -v ./... -race -tags=integration

before_script:
  - ./scripts/run-datastore-emulator.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
