language: go

go:
 - 1.12.x
 - 1.13.x

os: linux
dist: xenial

sudo: false

install:
  - go get -u github.com/golang/protobuf/protoc-gen-go
  - curl -L https://github.com/protocolbuffers/protobuf/releases/download/v3.9.1/protoc-3.9.1-linux-x86_64.zip -o /tmp/protoc.zip
  - unzip /tmp/protoc.zip -d "$HOME"/protoc
  - mkdir -p "$HOME"/src && ln -s "$HOME"/protoc "$HOME"/src/protobuf
  - ./scripts/run-datastore-emulator.sh

env:
  - PATH=$HOME/protoc/bin:$PATH DATASTORE_EMULATOR_HOST=127.0.0.1:8081 GO111MODULE="on"

script:
  - echo "Generate Protobuf's"
  - make protobuf
  - echo "Unit Tests"
  - make unit-tests
  - echo "Integration Tests"
  - make integration-tests

notifications:
  email:
    on_success: change
    on_failure: always

after_success:
  - bash <(curl -s https://codecov.io/bash)
