// Code generated by protoc-gen-go. DO NOT EDIT.
// source: execution.proto

package execution

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	_struct "github.com/golang/protobuf/ptypes/struct"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ExecutionRequest struct {
	Uuid                 string               `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Action               string               `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	StartedOn            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=started_on,json=startedOn,proto3" json:"started_on,omitempty"`
	Parameters           *_struct.Struct      `protobuf:"bytes,4,opt,name=parameters,proto3" json:"parameters,omitempty"`
	Result               []byte               `protobuf:"bytes,5,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ExecutionRequest) Reset()         { *m = ExecutionRequest{} }
func (m *ExecutionRequest) String() string { return proto.CompactTextString(m) }
func (*ExecutionRequest) ProtoMessage()    {}
func (*ExecutionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_776e2c5022e94aef, []int{0}
}

func (m *ExecutionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecutionRequest.Unmarshal(m, b)
}
func (m *ExecutionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecutionRequest.Marshal(b, m, deterministic)
}
func (m *ExecutionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecutionRequest.Merge(m, src)
}
func (m *ExecutionRequest) XXX_Size() int {
	return xxx_messageInfo_ExecutionRequest.Size(m)
}
func (m *ExecutionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecutionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExecutionRequest proto.InternalMessageInfo

func (m *ExecutionRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *ExecutionRequest) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *ExecutionRequest) GetStartedOn() *timestamp.Timestamp {
	if m != nil {
		return m.StartedOn
	}
	return nil
}

func (m *ExecutionRequest) GetParameters() *_struct.Struct {
	if m != nil {
		return m.Parameters
	}
	return nil
}

func (m *ExecutionRequest) GetResult() []byte {
	if m != nil {
		return m.Result
	}
	return nil
}

type Parent struct {
	Details              *_struct.Struct `protobuf:"bytes,1,opt,name=details,proto3" json:"details,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Parent) Reset()         { *m = Parent{} }
func (m *Parent) String() string { return proto.CompactTextString(m) }
func (*Parent) ProtoMessage()    {}
func (*Parent) Descriptor() ([]byte, []int) {
	return fileDescriptor_776e2c5022e94aef, []int{1}
}

func (m *Parent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Parent.Unmarshal(m, b)
}
func (m *Parent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Parent.Marshal(b, m, deterministic)
}
func (m *Parent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Parent.Merge(m, src)
}
func (m *Parent) XXX_Size() int {
	return xxx_messageInfo_Parent.Size(m)
}
func (m *Parent) XXX_DiscardUnknown() {
	xxx_messageInfo_Parent.DiscardUnknown(m)
}

var xxx_messageInfo_Parent proto.InternalMessageInfo

func (m *Parent) GetDetails() *_struct.Struct {
	if m != nil {
		return m.Details
	}
	return nil
}

type Child struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Parent               *Parent  `protobuf:"bytes,2,opt,name=parent,proto3" json:"parent,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Child) Reset()         { *m = Child{} }
func (m *Child) String() string { return proto.CompactTextString(m) }
func (*Child) ProtoMessage()    {}
func (*Child) Descriptor() ([]byte, []int) {
	return fileDescriptor_776e2c5022e94aef, []int{2}
}

func (m *Child) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Child.Unmarshal(m, b)
}
func (m *Child) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Child.Marshal(b, m, deterministic)
}
func (m *Child) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Child.Merge(m, src)
}
func (m *Child) XXX_Size() int {
	return xxx_messageInfo_Child.Size(m)
}
func (m *Child) XXX_DiscardUnknown() {
	xxx_messageInfo_Child.DiscardUnknown(m)
}

var xxx_messageInfo_Child proto.InternalMessageInfo

func (m *Child) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Child) GetParent() *Parent {
	if m != nil {
		return m.Parent
	}
	return nil
}

var E_ExcludeFromIndex = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         50000,
	Name:          "exclude_from_index",
	Tag:           "varint,50000,opt,name=exclude_from_index",
	Filename:      "execution.proto",
}

func init() {
	proto.RegisterType((*ExecutionRequest)(nil), "ExecutionRequest")
	proto.RegisterType((*Parent)(nil), "Parent")
	proto.RegisterType((*Child)(nil), "Child")
	proto.RegisterExtension(E_ExcludeFromIndex)
}

func init() { proto.RegisterFile("execution.proto", fileDescriptor_776e2c5022e94aef) }

var fileDescriptor_776e2c5022e94aef = []byte{
	// 337 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0xcd, 0x6a, 0xe3, 0x30,
	0x14, 0x85, 0xf1, 0x4c, 0xe2, 0x4c, 0x6e, 0x06, 0x26, 0x68, 0x31, 0x35, 0x21, 0x25, 0x26, 0xab,
	0xac, 0x1c, 0x9a, 0xae, 0xfa, 0xb7, 0x69, 0x69, 0xa0, 0x8b, 0x92, 0xe2, 0x76, 0x1f, 0x14, 0xeb,
	0x26, 0x15, 0xd8, 0x96, 0x2b, 0x5d, 0x41, 0x96, 0x5d, 0xf5, 0x8d, 0xfa, 0x1e, 0x5d, 0xf5, 0x79,
	0x8a, 0x15, 0x19, 0x4a, 0x42, 0x77, 0xf7, 0xe7, 0x3b, 0x3a, 0xba, 0x07, 0xfe, 0xe1, 0x16, 0x33,
	0x4b, 0x52, 0x95, 0x49, 0xa5, 0x15, 0xa9, 0xc1, 0x68, 0xa3, 0xd4, 0x26, 0xc7, 0xa9, 0xeb, 0x56,
	0x76, 0x3d, 0x25, 0x59, 0xa0, 0x21, 0x5e, 0x54, 0x1e, 0x18, 0xee, 0x03, 0x86, 0xb4, 0xcd, 0xc8,
	0x6f, 0xe3, 0xfd, 0xad, 0x40, 0x93, 0x69, 0x59, 0x91, 0xd2, 0x3b, 0x62, 0xfc, 0x19, 0x40, 0xff,
	0xb6, 0x31, 0x4d, 0xf1, 0xc5, 0xa2, 0x21, 0xc6, 0xa0, 0x65, 0xad, 0x14, 0x51, 0x10, 0x07, 0x93,
	0x6e, 0xea, 0x6a, 0xf6, 0x1f, 0x42, 0x9e, 0xd5, 0x50, 0xf4, 0xcb, 0x4d, 0x7d, 0xc7, 0xce, 0x00,
	0x0c, 0x71, 0x4d, 0x28, 0x96, 0xaa, 0x8c, 0x7e, 0xc7, 0xc1, 0xa4, 0x37, 0x1b, 0x24, 0x3b, 0xdf,
	0xa4, 0xf1, 0x4d, 0x9e, 0x9a, 0x6f, 0xa7, 0x5d, 0x4f, 0x2f, 0x4a, 0x76, 0x05, 0x50, 0x71, 0xcd,
	0x0b, 0x24, 0xd4, 0x26, 0x6a, 0x39, 0xe9, 0xd1, 0x81, 0xf4, 0xd1, 0x1d, 0x74, 0xdd, 0x7a, 0x7d,
	0x8f, 0x82, 0xf4, 0x9b, 0x80, 0x0d, 0x21, 0xd4, 0x68, 0x6c, 0x4e, 0x51, 0x3b, 0x0e, 0x26, 0x7f,
	0x3d, 0xe1, 0x67, 0xe3, 0x0b, 0x08, 0x1f, 0xb8, 0xc6, 0x92, 0xd8, 0x09, 0x74, 0x04, 0x12, 0x97,
	0xb9, 0x71, 0x07, 0xfd, 0xec, 0x91, 0x36, 0xdc, 0xf8, 0x12, 0xda, 0x37, 0xcf, 0x32, 0x17, 0x75,
	0x12, 0x25, 0x2f, 0xb0, 0x49, 0xa2, 0xae, 0xd9, 0x08, 0xc2, 0xca, 0xbd, 0xec, 0x92, 0xe8, 0xcd,
	0x3a, 0xc9, 0xce, 0x28, 0xf5, 0xe3, 0xf3, 0x7b, 0x60, 0xb8, 0xcd, 0x72, 0x2b, 0x70, 0xb9, 0xd6,
	0xaa, 0x58, 0xca, 0x52, 0xe0, 0x96, 0x1d, 0x1f, 0xb8, 0xce, 0x25, 0xe6, 0x62, 0x51, 0xd5, 0x31,
	0x9a, 0xe8, 0xe3, 0xad, 0xce, 0xee, 0x4f, 0xda, 0xf7, 0xd2, 0xb9, 0x56, 0xc5, 0x5d, 0x2d, 0x5c,
	0x85, 0x4e, 0x70, 0xfa, 0x15, 0x00, 0x00, 0xff, 0xff, 0x3a, 0x89, 0xfe, 0x62, 0x1d, 0x02, 0x00,
	0x00,
}
