// Code generated by protoc-gen-go. DO NOT EDIT.
// source: execution.proto

package execution

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	_struct "github.com/golang/protobuf/ptypes/struct"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ExecutionRequest struct {
	Uuid                 string               `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Action               string               `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	StartedOn            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=started_on,json=startedOn,proto3" json:"started_on,omitempty"`
	Parameters           *_struct.Struct      `protobuf:"bytes,4,opt,name=parameters,proto3" json:"parameters,omitempty"`
	Result               []byte               `protobuf:"bytes,5,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ExecutionRequest) Reset()         { *m = ExecutionRequest{} }
func (m *ExecutionRequest) String() string { return proto.CompactTextString(m) }
func (*ExecutionRequest) ProtoMessage()    {}
func (*ExecutionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_776e2c5022e94aef, []int{0}
}

func (m *ExecutionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecutionRequest.Unmarshal(m, b)
}
func (m *ExecutionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecutionRequest.Marshal(b, m, deterministic)
}
func (m *ExecutionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecutionRequest.Merge(m, src)
}
func (m *ExecutionRequest) XXX_Size() int {
	return xxx_messageInfo_ExecutionRequest.Size(m)
}
func (m *ExecutionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecutionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExecutionRequest proto.InternalMessageInfo

func (m *ExecutionRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *ExecutionRequest) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *ExecutionRequest) GetStartedOn() *timestamp.Timestamp {
	if m != nil {
		return m.StartedOn
	}
	return nil
}

func (m *ExecutionRequest) GetParameters() *_struct.Struct {
	if m != nil {
		return m.Parameters
	}
	return nil
}

func (m *ExecutionRequest) GetResult() []byte {
	if m != nil {
		return m.Result
	}
	return nil
}

type Action struct {
	Name                 string          `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Parameters           *_struct.Struct `protobuf:"bytes,2,opt,name=parameters,proto3" json:"parameters,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Action) Reset()         { *m = Action{} }
func (m *Action) String() string { return proto.CompactTextString(m) }
func (*Action) ProtoMessage()    {}
func (*Action) Descriptor() ([]byte, []int) {
	return fileDescriptor_776e2c5022e94aef, []int{1}
}

func (m *Action) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Action.Unmarshal(m, b)
}
func (m *Action) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Action.Marshal(b, m, deterministic)
}
func (m *Action) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Action.Merge(m, src)
}
func (m *Action) XXX_Size() int {
	return xxx_messageInfo_Action.Size(m)
}
func (m *Action) XXX_DiscardUnknown() {
	xxx_messageInfo_Action.DiscardUnknown(m)
}

var xxx_messageInfo_Action proto.InternalMessageInfo

func (m *Action) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Action) GetParameters() *_struct.Struct {
	if m != nil {
		return m.Parameters
	}
	return nil
}

type Execution struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Action               *Action  `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Execution) Reset()         { *m = Execution{} }
func (m *Execution) String() string { return proto.CompactTextString(m) }
func (*Execution) ProtoMessage()    {}
func (*Execution) Descriptor() ([]byte, []int) {
	return fileDescriptor_776e2c5022e94aef, []int{2}
}

func (m *Execution) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Execution.Unmarshal(m, b)
}
func (m *Execution) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Execution.Marshal(b, m, deterministic)
}
func (m *Execution) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Execution.Merge(m, src)
}
func (m *Execution) XXX_Size() int {
	return xxx_messageInfo_Execution.Size(m)
}
func (m *Execution) XXX_DiscardUnknown() {
	xxx_messageInfo_Execution.DiscardUnknown(m)
}

var xxx_messageInfo_Execution proto.InternalMessageInfo

func (m *Execution) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Execution) GetAction() *Action {
	if m != nil {
		return m.Action
	}
	return nil
}

var E_ExcludeFromIndex = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         50000,
	Name:          "exclude_from_index",
	Tag:           "varint,50000,opt,name=exclude_from_index",
	Filename:      "execution.proto",
}

func init() {
	proto.RegisterType((*ExecutionRequest)(nil), "ExecutionRequest")
	proto.RegisterType((*Action)(nil), "Action")
	proto.RegisterType((*Execution)(nil), "Execution")
	proto.RegisterExtension(E_ExcludeFromIndex)
}

func init() { proto.RegisterFile("execution.proto", fileDescriptor_776e2c5022e94aef) }

var fileDescriptor_776e2c5022e94aef = []byte{
	// 328 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0x4f, 0x4b, 0xf3, 0x40,
	0x10, 0xc6, 0x49, 0xdf, 0xbc, 0xd1, 0x4e, 0x05, 0xcb, 0x1e, 0x74, 0x29, 0x95, 0x86, 0x9e, 0x7a,
	0x4a, 0xa1, 0x1e, 0x44, 0x41, 0x50, 0xc1, 0x82, 0x07, 0x29, 0x44, 0x3d, 0x97, 0x34, 0x99, 0x96,
	0x40, 0x92, 0x8d, 0xbb, 0xb3, 0xd0, 0xa3, 0x27, 0xbf, 0x91, 0xdf, 0xc3, 0x93, 0x9f, 0x47, 0xb2,
	0xd9, 0x48, 0xff, 0x88, 0xb7, 0x9d, 0x99, 0xe7, 0xd9, 0xdf, 0xcc, 0x03, 0xc7, 0xb8, 0xc6, 0x58,
	0x53, 0x2a, 0x8a, 0xa0, 0x94, 0x82, 0x44, 0x6f, 0xb0, 0x12, 0x62, 0x95, 0xe1, 0xd8, 0x54, 0x0b,
	0xbd, 0x1c, 0x53, 0x9a, 0xa3, 0xa2, 0x28, 0x2f, 0xad, 0xa0, 0xbf, 0x2b, 0x50, 0x24, 0x75, 0x4c,
	0x76, 0xea, 0xef, 0x4e, 0x13, 0x54, 0xb1, 0x4c, 0x4b, 0x12, 0xb2, 0x56, 0x0c, 0xbf, 0x1c, 0xe8,
	0xde, 0x37, 0xd0, 0x10, 0x5f, 0x35, 0x2a, 0x62, 0x0c, 0x5c, 0xad, 0xd3, 0x84, 0x3b, 0xbe, 0x33,
	0x6a, 0x87, 0xe6, 0xcd, 0x4e, 0xc0, 0x8b, 0xe2, 0x4a, 0xc4, 0x5b, 0xa6, 0x6b, 0x2b, 0x76, 0x09,
	0xa0, 0x28, 0x92, 0x84, 0xc9, 0x5c, 0x14, 0xfc, 0x9f, 0xef, 0x8c, 0x3a, 0x93, 0x5e, 0x50, 0x73,
	0x83, 0x86, 0x1b, 0x3c, 0x37, 0x6b, 0x87, 0x6d, 0xab, 0x9e, 0x15, 0xec, 0x1a, 0xa0, 0x8c, 0x64,
	0x94, 0x23, 0xa1, 0x54, 0xdc, 0x35, 0xd6, 0xd3, 0x3d, 0xeb, 0x93, 0x39, 0xe8, 0xce, 0x7d, 0xfb,
	0xe0, 0x4e, 0xb8, 0x61, 0x60, 0x7d, 0xf0, 0x24, 0x2a, 0x9d, 0x11, 0xff, 0xef, 0x3b, 0xa3, 0x23,
	0xab, 0xb0, 0xbd, 0xe1, 0x0b, 0x78, 0xb7, 0xf5, 0x86, 0x0c, 0xdc, 0x22, 0xca, 0xb1, 0xb9, 0xa6,
	0x7a, 0xb3, 0x8b, 0x2d, 0x74, 0xeb, 0x4f, 0xf4, 0x26, 0x74, 0x78, 0x03, 0xed, 0x9f, 0xb8, 0x7e,
	0xfd, 0x79, 0xb0, 0x95, 0x53, 0x67, 0x72, 0x10, 0xd4, 0x6b, 0x34, 0x81, 0x5d, 0x3d, 0x02, 0xc3,
	0x75, 0x9c, 0xe9, 0x04, 0xe7, 0x4b, 0x29, 0xf2, 0x79, 0x5a, 0x24, 0xb8, 0x66, 0x67, 0x7b, 0xf0,
	0x69, 0x8a, 0x59, 0x32, 0x2b, 0x2b, 0x8f, 0xe2, 0x9f, 0xef, 0x55, 0xb2, 0x87, 0x61, 0xd7, 0x5a,
	0xa7, 0x52, 0xe4, 0x0f, 0x95, 0x71, 0xe1, 0x19, 0xc3, 0xf9, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x15, 0xb1, 0x39, 0x0b, 0x3b, 0x02, 0x00, 0x00,
}
