// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/unsupported.proto

package unsupported

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_struct "github.com/golang/protobuf/ptypes/struct"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Model struct {
	Uint32Key            uint32   `protobuf:"varint,1,opt,name=uint32_key,json=uint32Key,proto3" json:"uint32_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Model) Reset()         { *m = Model{} }
func (m *Model) String() string { return proto.CompactTextString(m) }
func (*Model) ProtoMessage()    {}
func (*Model) Descriptor() ([]byte, []int) {
	return fileDescriptor_1dbaeb655f16b474, []int{0}
}

func (m *Model) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Model.Unmarshal(m, b)
}
func (m *Model) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Model.Marshal(b, m, deterministic)
}
func (m *Model) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Model.Merge(m, src)
}
func (m *Model) XXX_Size() int {
	return xxx_messageInfo_Model.Size(m)
}
func (m *Model) XXX_DiscardUnknown() {
	xxx_messageInfo_Model.DiscardUnknown(m)
}

var xxx_messageInfo_Model proto.InternalMessageInfo

func (m *Model) GetUint32Key() uint32 {
	if m != nil {
		return m.Uint32Key
	}
	return 0
}

type TS struct {
	StartedOn            *timestamp.Timestamp `protobuf:"bytes,1,opt,name=StartedOn,proto3" json:"StartedOn,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *TS) Reset()         { *m = TS{} }
func (m *TS) String() string { return proto.CompactTextString(m) }
func (*TS) ProtoMessage()    {}
func (*TS) Descriptor() ([]byte, []int) {
	return fileDescriptor_1dbaeb655f16b474, []int{1}
}

func (m *TS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TS.Unmarshal(m, b)
}
func (m *TS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TS.Marshal(b, m, deterministic)
}
func (m *TS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TS.Merge(m, src)
}
func (m *TS) XXX_Size() int {
	return xxx_messageInfo_TS.Size(m)
}
func (m *TS) XXX_DiscardUnknown() {
	xxx_messageInfo_TS.DiscardUnknown(m)
}

var xxx_messageInfo_TS proto.InternalMessageInfo

func (m *TS) GetStartedOn() *timestamp.Timestamp {
	if m != nil {
		return m.StartedOn
	}
	return nil
}

type StructMessage struct {
	StructKey            *_struct.Struct `protobuf:"bytes,1,opt,name=StructKey,proto3" json:"StructKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *StructMessage) Reset()         { *m = StructMessage{} }
func (m *StructMessage) String() string { return proto.CompactTextString(m) }
func (*StructMessage) ProtoMessage()    {}
func (*StructMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_1dbaeb655f16b474, []int{2}
}

func (m *StructMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StructMessage.Unmarshal(m, b)
}
func (m *StructMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StructMessage.Marshal(b, m, deterministic)
}
func (m *StructMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StructMessage.Merge(m, src)
}
func (m *StructMessage) XXX_Size() int {
	return xxx_messageInfo_StructMessage.Size(m)
}
func (m *StructMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_StructMessage.DiscardUnknown(m)
}

var xxx_messageInfo_StructMessage proto.InternalMessageInfo

func (m *StructMessage) GetStructKey() *_struct.Struct {
	if m != nil {
		return m.StructKey
	}
	return nil
}

type Parent struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Parent) Reset()         { *m = Parent{} }
func (m *Parent) String() string { return proto.CompactTextString(m) }
func (*Parent) ProtoMessage()    {}
func (*Parent) Descriptor() ([]byte, []int) {
	return fileDescriptor_1dbaeb655f16b474, []int{3}
}

func (m *Parent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Parent.Unmarshal(m, b)
}
func (m *Parent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Parent.Marshal(b, m, deterministic)
}
func (m *Parent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Parent.Merge(m, src)
}
func (m *Parent) XXX_Size() int {
	return xxx_messageInfo_Parent.Size(m)
}
func (m *Parent) XXX_DiscardUnknown() {
	xxx_messageInfo_Parent.DiscardUnknown(m)
}

var xxx_messageInfo_Parent proto.InternalMessageInfo

func (m *Parent) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Child struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Parent               *Parent  `protobuf:"bytes,2,opt,name=Parent,proto3" json:"Parent,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Child) Reset()         { *m = Child{} }
func (m *Child) String() string { return proto.CompactTextString(m) }
func (*Child) ProtoMessage()    {}
func (*Child) Descriptor() ([]byte, []int) {
	return fileDescriptor_1dbaeb655f16b474, []int{4}
}

func (m *Child) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Child.Unmarshal(m, b)
}
func (m *Child) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Child.Marshal(b, m, deterministic)
}
func (m *Child) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Child.Merge(m, src)
}
func (m *Child) XXX_Size() int {
	return xxx_messageInfo_Child.Size(m)
}
func (m *Child) XXX_DiscardUnknown() {
	xxx_messageInfo_Child.DiscardUnknown(m)
}

var xxx_messageInfo_Child proto.InternalMessageInfo

func (m *Child) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Child) GetParent() *Parent {
	if m != nil {
		return m.Parent
	}
	return nil
}

func init() {
	proto.RegisterType((*Model)(nil), "Model")
	proto.RegisterType((*TS)(nil), "TS")
	proto.RegisterType((*StructMessage)(nil), "StructMessage")
	proto.RegisterType((*Parent)(nil), "Parent")
	proto.RegisterType((*Child)(nil), "Child")
}

func init() { proto.RegisterFile("proto/unsupported.proto", fileDescriptor_1dbaeb655f16b474) }

var fileDescriptor_1dbaeb655f16b474 = []byte{
	// 241 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x8e, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0x69, 0xb1, 0x95, 0x4c, 0xe9, 0x65, 0x2f, 0x2d, 0xa5, 0x52, 0xd9, 0x83, 0x78, 0xda,
	0x40, 0x8a, 0xe0, 0x41, 0xbc, 0x08, 0x5e, 0x4a, 0x55, 0x36, 0xbd, 0xcb, 0xd6, 0x8c, 0x31, 0x98,
	0x64, 0x43, 0x76, 0xf6, 0xd0, 0x7f, 0x2f, 0x99, 0x4d, 0x28, 0xa8, 0xb7, 0x9d, 0x37, 0xdf, 0xbc,
	0x6f, 0x61, 0xd1, 0xb4, 0x96, 0x6c, 0xec, 0x6b, 0xe7, 0x9b, 0xc6, 0xb6, 0x84, 0x99, 0xe2, 0x64,
	0xb5, 0xc9, 0xad, 0xcd, 0x4b, 0x8c, 0x79, 0x3a, 0xfa, 0xcf, 0x98, 0x8a, 0x0a, 0x1d, 0x99, 0xaa,
	0xe9, 0x81, 0xf5, 0x6f, 0xc0, 0x51, 0xeb, 0x3f, 0x28, 0x6c, 0xe5, 0x0d, 0x4c, 0xf6, 0x36, 0xc3,
	0x52, 0x5c, 0x01, 0xf8, 0xa2, 0xa6, 0x6d, 0xf2, 0xfe, 0x8d, 0xa7, 0xe5, 0xe8, 0x7a, 0x74, 0x3b,
	0xd7, 0x51, 0x48, 0x76, 0x78, 0x92, 0x8f, 0x30, 0x3e, 0xa4, 0xe2, 0x1e, 0xa2, 0x94, 0x4c, 0x67,
	0x7f, 0xad, 0x99, 0x99, 0x25, 0x2b, 0x15, 0xfa, 0xd5, 0xd0, 0xaf, 0x0e, 0xc3, 0x07, 0xf4, 0x19,
	0x96, 0xcf, 0x30, 0x4f, 0xd9, 0xbb, 0x47, 0xe7, 0x4c, 0x8e, 0xe2, 0xae, 0xab, 0xea, 0x82, 0x5d,
	0xaf, 0x9b, 0x25, 0x8b, 0x3f, 0x55, 0x81, 0xd0, 0x67, 0x52, 0xae, 0x61, 0xfa, 0x66, 0x5a, 0xac,
	0x49, 0x08, 0xb8, 0x78, 0x31, 0x15, 0xf2, 0x6d, 0xa4, 0xf9, 0x2d, 0x1f, 0x60, 0xf2, 0xf4, 0x55,
	0x94, 0xd9, 0x7f, 0x4b, 0xb1, 0x19, 0x4e, 0x97, 0x63, 0xd6, 0x5d, 0xaa, 0x30, 0xea, 0x3e, 0x3e,
	0x4e, 0xd9, 0xbb, 0xfd, 0x09, 0x00, 0x00, 0xff, 0xff, 0xe6, 0xd5, 0xa8, 0xac, 0x6c, 0x01, 0x00,
	0x00,
}
