// Code generated by protoc-gen-go. DO NOT EDIT.
// source: execution.proto

package execution

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_struct "github.com/golang/protobuf/ptypes/struct"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ExecutionRequest struct {
	Uuid                 string               `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Action               string               `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	StartedOn            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=started_on,json=startedOn,proto3" json:"started_on,omitempty"`
	Parameters           *_struct.Struct      `protobuf:"bytes,4,opt,name=parameters,proto3" json:"parameters,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ExecutionRequest) Reset()         { *m = ExecutionRequest{} }
func (m *ExecutionRequest) String() string { return proto.CompactTextString(m) }
func (*ExecutionRequest) ProtoMessage()    {}
func (*ExecutionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_776e2c5022e94aef, []int{0}
}

func (m *ExecutionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecutionRequest.Unmarshal(m, b)
}
func (m *ExecutionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecutionRequest.Marshal(b, m, deterministic)
}
func (m *ExecutionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecutionRequest.Merge(m, src)
}
func (m *ExecutionRequest) XXX_Size() int {
	return xxx_messageInfo_ExecutionRequest.Size(m)
}
func (m *ExecutionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecutionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExecutionRequest proto.InternalMessageInfo

func (m *ExecutionRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *ExecutionRequest) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *ExecutionRequest) GetStartedOn() *timestamp.Timestamp {
	if m != nil {
		return m.StartedOn
	}
	return nil
}

func (m *ExecutionRequest) GetParameters() *_struct.Struct {
	if m != nil {
		return m.Parameters
	}
	return nil
}

func init() {
	proto.RegisterType((*ExecutionRequest)(nil), "ExecutionRequest")
}

func init() { proto.RegisterFile("execution.proto", fileDescriptor_776e2c5022e94aef) }

var fileDescriptor_776e2c5022e94aef = []byte{
	// 194 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4f, 0xad, 0x48, 0x4d,
	0x2e, 0x2d, 0xc9, 0xcc, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x97, 0x92, 0x4f, 0xcf, 0xcf,
	0x4f, 0xcf, 0x49, 0xd5, 0x07, 0xf3, 0x92, 0x4a, 0xd3, 0xf4, 0x4b, 0x32, 0x73, 0x53, 0x8b, 0x4b,
	0x12, 0x73, 0x0b, 0xa0, 0x0a, 0x64, 0xd0, 0x15, 0x14, 0x97, 0x14, 0x95, 0x26, 0x97, 0x40, 0x64,
	0x95, 0x36, 0x31, 0x72, 0x09, 0xb8, 0xc2, 0x8c, 0x0c, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11,
	0x12, 0xe2, 0x62, 0x29, 0x2d, 0xcd, 0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3,
	0x85, 0xc4, 0xb8, 0xd8, 0x12, 0x93, 0x41, 0x8a, 0x24, 0x98, 0xc0, 0xa2, 0x50, 0x9e, 0x90, 0x25,
	0x17, 0x57, 0x71, 0x49, 0x62, 0x51, 0x49, 0x6a, 0x4a, 0x7c, 0x7e, 0x9e, 0x04, 0xb3, 0x02, 0xa3,
	0x06, 0xb7, 0x91, 0x94, 0x1e, 0xc4, 0x4e, 0x3d, 0x98, 0x9d, 0x7a, 0x21, 0x30, 0x47, 0x05, 0x71,
	0x42, 0x55, 0xfb, 0xe7, 0x09, 0x99, 0x73, 0x71, 0x15, 0x24, 0x16, 0x25, 0xe6, 0xa6, 0x96, 0xa4,
	0x16, 0x15, 0x4b, 0xb0, 0x80, 0xb5, 0x8a, 0x63, 0x68, 0x0d, 0x06, 0x3b, 0x37, 0x08, 0x49, 0x69,
	0x12, 0x1b, 0x58, 0xd2, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x59, 0x0c, 0x64, 0x1a, 0x0d, 0x01,
	0x00, 0x00,
}
